
development:
  adapter: postgresql
  host: localhost
  database: freaktags_dev
  user: freaktags_dev
  password: freaktags_dev
  pool: 30

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5

beta:
  adapter: postgresql
  url: <%= ENV['FT_BETA_DATABASE_URL'] %>
  pool: 30

production:
  adapter: postgresql
  url: <%= ENV['FT_PROD_DATABASE_URL'] %>
  pool: 30
